config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subway.urls')),
    path('crud/', include('crud.urls'))
]

crud/urls.py
from django.urls import path
from . import views 

app_name = "crud"
urlpatterns = [
    path('new/', views.new, name='new'), #crud/new/
    # path('create/', views.create, name='create'), #crud/create/
    path('', views.index, name='index'), #crud/
    # crud/pk/article/ detail page
    path('<int:pk>/detail/', views.detail, name='detail'), # 해당 url로 가면 views.detail 실행하겠다!
    # crud/pk/update/ 수정 페이지
    path('<int:pk>/update/', views.update, name='update'),
    # crud/pk/revise/ 최종 업데이트
    # path('<int:pk>/revise/', views.revise, name='revise'),
    # crud/pk/delete/ 삭제하기
    path('<int:pk>/delete/', views.delete, name='delete'),
]

subway/urls.py
from django.urls import path
from . import views

app_name = "subway" # path 이름이 겹쳐서 name space를 사용할 때 문제가 생길 경우를 대비해 appname을 설정해 줄 수 있다. 
urlpatterns = [
    # name을 설정하면 url 관리가 수월하다.
    # {% url 'app_name:설정name' %} 방식으로 사용
    # url이 바뀌어도 일일이 찾아서 바꿀 필요가 없다.
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),
    # {% url 'app_name:설정name' 넘길데이터1 넘길데이터2 %}
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    # path('<int:pk>/change/', views.change, name='change'),
    path('<int:pk>/delete/', views.delete, name='delete')
]

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'subway:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'subway:new' %}">New Order</a>
            </li>
          </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>